### ISSUE TITLE
Clarify which zone origin in being discussed

### ISSUE THREAD

**Issue by paulehoffman** [ietf-wg-dnsop/draft-ietf-dnsop-rfc8499bis#13]
Change:
`(rarely) the same as the zone origin and not subordinate to or the same as the`
To:
`(rarely) the same as the zone origin of the parent and not subordinate to or the same as the`

**Comment by kfujiwara** [comment]
"the parent" is ambiguous for me.  Whose parent is it ?
"Sibling domain" is a type of relationships between the owner name of the record and the name in the NS RDATA and the zone origin. Then, "the zone origin" is the origin of the zone which have the NS Resource Record.
